# I. Numpy

### Импортируйте NumPy

In [4]:
import numpy as np


### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [5]:
np_array = np.zeros(10)
np_array[4] = 1
np_marix = np_array.reshape(2, 5)
print(np_marix)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [20]:
np_array = np.random.randint(10, 49, 10)
print(np_array)
np_array_reversed = np.flip(np_array)
print(np_array_reversed)
np_array_reversed_filtered = np_array_reversed[(np_array_reversed % 2 == 0)]
print(np_array_reversed_filtered)

[22 41 39 23 37 28 24 48 31 38]
[38 31 48 24 28 37 23 39 41 22]
[38 48 24 28 22]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [24]:
np_array = np.random.randint(0, 8, [3,3])
print(np_array)

[[5 4 7]
 [3 0 0]
 [6 6 7]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [44]:
np_array = np.random.random([4,3,2])
print(np_array)
print(np_array.shape)
min = np.min(np_array)
print(min)

[[[0.06410421 0.39482594]
  [0.96099883 0.9843217 ]
  [0.7668323  0.84833665]]

 [[0.90677013 0.94529226]
  [0.86523549 0.24971325]
  [0.42203187 0.85473326]]

 [[0.82212346 0.55602916]
  [0.92665605 0.22725525]
  [0.37949424 0.53546238]]

 [[0.81691956 0.92624723]
  [0.34299791 0.21056717]
  [0.21221132 0.30757539]]]
(4, 3, 2)
0.06410420852315857


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [46]:
a1 = np.random.random([6,4])
a2 = np.random.random([4,3])
a3 = np.matmul(a1, a2)
print(a1)
print(a2)
print(a3)

[[0.84768622 0.52497942 0.65280145 0.86119273]
 [0.11411069 0.20990145 0.59681936 0.83068778]
 [0.95105226 0.36669088 0.20347655 0.04537833]
 [0.37087334 0.77890869 0.63385159 0.76087324]
 [0.72733968 0.40263854 0.56265417 0.76226785]
 [0.1708933  0.68098829 0.56437876 0.63861644]]
[[0.99869234 0.75656377 0.49496058]
 [0.47824369 0.14429774 0.07428705]
 [0.67597371 0.76597327 0.59311246]
 [0.00165291 0.93529018 0.88058776]]
[[1.54034592 2.02257559 1.60411088]
 [0.61915277 1.35070211 1.15754774]
 [1.26279602 0.97074385 0.65861784]
 [1.1726212  1.59013474 1.28739146]
 [1.3005473  1.75229838 1.39487624]
 [0.87890897 1.25714748 1.03227196]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [50]:
np_array = np.random.random([7,7])
std = np.std(np_array)
mean = np.mean(np_array)
normalized = np.normalize(np_array)
print(std)
print(mean)
print(normalized)

AttributeError: module 'numpy' has no attribute 'normalize'

# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

### Загрузите датасет Tips из набора датасетов seaborn

### Посмотрите на первые 5 строчек

### Узнайте сколько всего строчек и колонок в данных

### Проверьте есть ли пропуски в данных

### Посмотрите на распределение числовых признаков

### Найдите максимальное значение 'total_bill'

### Найдите количество курящих людей

### Узнайте какой средний 'total_bill' в зависимости от 'day'

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.