# I. Numpy

### Импортируйте NumPy

In [147]:
import numpy as np


### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [148]:
np_array = np.zeros(10)
np_array[4] = 1
np_marix = np_array.reshape(2, 5)
print(np_marix)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [149]:
np_array = np.random.randint(10, 49, 10)
print(np_array)
np_array_reversed = np.flip(np_array)
print(np_array_reversed)
np_array_reversed_filtered = np_array_reversed[(np_array_reversed % 2 == 0)]
print(np_array_reversed_filtered)

[38 23 18 15 18 30 46 44 32 35]
[35 32 44 46 30 18 15 18 23 38]
[32 44 46 30 18 18 38]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [150]:
np_array = np.random.randint(0, 8, [3,3])
print(np_array)

[[3 7 1]
 [4 2 6]
 [3 7 7]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [151]:
np_array = np.random.random([4,3,2])
print(np_array)
print(np_array.shape)
min = np.min(np_array)
print(min)

[[[0.83697581 0.93574815]
  [0.61782518 0.42992074]
  [0.25579521 0.83677916]]

 [[0.85846127 0.59657771]
  [0.63785366 0.71974447]
  [0.52290642 0.54037648]]

 [[0.69193692 0.91298308]
  [0.62564825 0.68842088]
  [0.08525381 0.90873894]]

 [[0.04101653 0.83145589]
  [0.87396523 0.86790891]
  [0.76556015 0.28075381]]]
(4, 3, 2)
0.04101652786747012


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [152]:
a1 = np.random.random([6,4])
a2 = np.random.random([4,3])
a3 = np.matmul(a1, a2)
print(a1)
print(a2)
print(a3)

[[0.82985098 0.87693598 0.80293059 0.86968486]
 [0.28087152 0.99249708 0.037745   0.08160406]
 [0.4580297  0.57761356 0.73030422 0.43913935]
 [0.77628406 0.53600382 0.62898858 0.78558392]
 [0.8672932  0.53719153 0.48588594 0.76625093]
 [0.56295206 0.84659702 0.00708512 0.72146542]]
[[0.21846194 0.9411693  0.0211946 ]
 [0.79485286 0.80305172 0.5521309 ]
 [0.03956028 0.38863478 0.60637096]
 [0.96752865 0.78765929 0.8246961 ]]
[[1.7515351  2.48231733 1.70587132]
 [0.93069634 1.14031935 0.64412729]
 [1.01295079 1.52465087 1.13361783]
 [1.38059061 2.02427283 1.34166572]
 [1.37705029 2.04003915 1.24153326]
 [1.49422241 1.78071685 1.07864985]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [153]:
np_array = np.random.random([7,7])
std = np.std(np_array)
mean = np.mean(np_array)
normalized = np.linalg.norm(np_array)
print(std)
print(mean)
print(normalized)

0.3339327147707174
0.47453559644567656
4.061780326915965


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [154]:
import pandas as pd
import matplotlib as mpl
import seaborn as sb

### Загрузите датасет Tips из набора датасетов seaborn

In [155]:
tips = sb.load_dataset("tips")

### Посмотрите на первые 5 строчек

In [156]:
first_5_rows = tips.head(5)
print(first_5_rows)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4


### Узнайте сколько всего строчек и колонок в данных

In [157]:
row_count = tips.size
column_count = tips.columns.size
print(row_count)
print(column_count)

1708
7


### Проверьте есть ли пропуски в данных

In [158]:
has_empty_values = tips.isnull().any()
print(has_empty_values)

total_bill    False
tip           False
sex           False
smoker        False
day           False
time          False
size          False
dtype: bool


### Посмотрите на распределение числовых признаков

### Найдите максимальное значение 'total_bill'

In [159]:
total_bill_max = tips.loc[:, 'total_bill'].max()
print(total_bill_max)

50.81


### Найдите количество курящих людей

In [160]:
smokers_count = tips.loc[(tips['smoker'] == "Yes")].size
print(smokers_count)

651


### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [161]:
total_bill_avg = tips.groupby('day').agg(Mean=('total_bill', np.mean))
print(total_bill_avg)

           Mean
day            
Thur  17.682742
Fri   17.151579
Sat   20.441379
Sun   21.410000


### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [162]:
total_bill_med = tips.loc[:, 'total_bill'].median()
filtered_tips = tips.loc[(tips['total_bill'] > total_bill_med)]
print(filtered_tips)
avg_tip_by_sex = tips.groupby('sex').agg(Mean=('tip', np.mean))
print(avg_tip_by_sex)

     total_bill   tip     sex smoker   day    time  size
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[122 rows x 7 columns]
            Mean
sex             
Male    3.089618
Female  2.833448


### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [177]:
def map(x):
    if (x == "Yes"): return '1'
    return '0'

for i, row in tips.iterrows():
    tips.at[i, 'smoker_bin'] = map(row['smoker'])

print(tips)


     total_bill   tip     sex smoker   day    time  size smoker_bin
0         16.99  1.01  Female     No   Sun  Dinner     2          0
1         10.34  1.66    Male     No   Sun  Dinner     3          0
2         21.01  3.50    Male     No   Sun  Dinner     3          0
3         23.68  3.31    Male     No   Sun  Dinner     2          0
4         24.59  3.61  Female     No   Sun  Dinner     4          0
..          ...   ...     ...    ...   ...     ...   ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3          0
240       27.18  2.00  Female    Yes   Sat  Dinner     2          1
241       22.67  2.00    Male    Yes   Sat  Dinner     2          1
242       17.82  1.75    Male     No   Sat  Dinner     2          0
243       18.78  3.00  Female     No  Thur  Dinner     2          0

[244 rows x 8 columns]


# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.